import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./lib/ui/header";
import { Suspense } from "react";
import { BasketProvider } from "./providers/basket-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BasketProvider>
          <Suspense fallback={<h1>Loading...</h1>}>
            <Header />
          </Suspense>
          {children}
        </BasketProvider>
      </body>
    </html>
  );
}
